# #### ENGLISH ####
# This is the world default configuration file for Plazma.
# As you can see, there's a lot to configure. Some options may impact
# gameplay, so use with caution, and make sure you know what each option
# does before configuring.
# 
# A description of the options can be found on the official wiki,
# If you need help with the configuration or have any questions related to Plazma,
# join us in our Discord for Plazma, or create issues on our GitHub repository.
# 
# World-specific settings can be set in the plazma-world.yml
# file within each world folder, and the same settings apply to all
# worlds unless they are overwritten through the world-specific settings file.
# 
# 
# #### 한국어 ####
# 본 파일은 Plazma의 월드 기본 구성 파일입니다.
# 보시다시피, 굉장히 많은 설정이 있습니다. 일부 설정은 게임 플레이에 영향을 줄 수 있습니다.
# 따라서 주의해서 사용하시고, 각 설정이 서버에 어떠한 작용을 하는지 숙지하고 사용하시기 바랍니다.
# 
# 구성에 대한 설명은 공식 위키에서 찾을 수 있으며,
# 만약 설정에 도움이 필요하거나, Plazma에 대해 질문이 있으시다면,
# 공식 Discord 서버에 접속하거나, GitHub 저장소에 이슈를 생성해주시기 바랍니다.
# 
# 월드별 설정은 각 월드 폴더 내 plazma-world.yml 파일에서 설정할 수
# 있으며, 월드별 설정을 통해 값을 덮어쓰지 않는 한, 모든 월드에 동일한 설정이 적용됩니다.
# 
# 
# GitHub: https://github.com/PlazmaMC/Plazma
# Wiki: https://docs.plazmamc.org/
# Discord: https://plazmamc.org/discord

_version: 2
block:
  hopper:
    full-cooldown: 0
  rail:
    use-faster-signal-search: true
  water-flowing-tick: 5
entity:
  phantom:
    load-chunks-to-spawn: false
  sensor-tick: 1
  spawn-deadlock-timer:
    enabled: true
    timer-timeout: 0
  suppress-errors-from-dirty-attributes: true
  wake-up-duration-variance:
    animal: 0.2
    flying: 0.2
    monster: 0.2
    villager: 0.2
misc:
  use-better-random-algorithm: false
